name: npm-pkg-lint
description: Run npm-pkg-lint on the package(s)
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
          path: ~/.cache/npm-pkg-lint
          key: npm-pkg-lint
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
          node-version: 20.x
    - name: Install dependencies
      shell: bash
      run: npm ci
    - name: Build
      shell: bash
      run: npm run --if-present build
    - name: npm-pkg-lint
      shell: bash
      run: |
        if [[ -e packages ]]; then
          for pkg in packages/*/; do (
              echo "::group::${pkg}"
              set -e
              cd $pkg
              npm pack
              npm exec npm-pkg-lint -- --allow-dependency fk-icons
              echo "::endgroup::"
          ); done
        else
          npm pack
          npm exec npm-pkg-lint -- --allow-dependency fk-icons
        fi
